import Head from 'next/head'
import TemporaryWelcomePage from '../src/components/TemporaryWelcomePage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TemporaryWelcomePage />    
      </main>
    </div>
  )
}
// var readJson = (path, cb) => {
//   fs.readFile(require.resolve(path), (err, data) => {
//     if (err)
//       cb(err)
//     else
//       cb(null, JSON.parse(data))
//   })
// }

// export function getStaticProps() {
//   const locales = readJson("../locales/en/common.json")
//   console.log(locales)
// }
